# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=
# Спасибо что скачали этот плагин, так вы даете мне знать,
# знать, что мой ресурс вам нужен.
# ===========================================================
# Пожалуйста, оставьте отзыв, если мой плагин вам понравился
# *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=

# %player% - выводит ник игрока

# Уменьшает наносимый урон вашей жертвой
AttackDamageReduce: # Тип пытки указываемый в команде
  # Mode: 0 - наносимый урон делится на ваше число
  # Mode: 1 - ваше число вычивается из наносимоего урона
  # Mode: 2 - любой урон блокируется
  Mode: 0
  Value: 2 # Число на которое делится/вычитается
  Time: 120 # Время до наказания в секундах
  Punishment: "kick %player% &cAC Вы были кикнуты за подозрение в читах"

# Рандомно ротатирует прицел игрока
RandomRotation:
  Time: 15 # Время до наказания в секундах
  Punishment: "kick %player% &cAC Вы были кикнуты за подозрение в читах"

# Устанавливает указанную walk скорость
SpeedReducer:
  Value: 0 # Устанавливаемая скорость
  Time: 120
  Punishment: "kick %player% &cAC Вы были кикнуты за подозрение в читах"

# Снимает указанное количество голода через указанное время
BigHunger:
  Value: 1 # Минусуемое значение из голода игрока
  timeToSetHunger: 2 # Время через которое снимет указанный голод
  Time: 60
  Punishment: "kick %player% &cAC Вы были кикнуты за подозрение в читах"

# Полностью отчищает инвентарь игрока
ClearInventory:
  Time: 15
  Punishment: "kick %player% &cAC Вы были кикнуты за подозрение в читах"